// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2A35KLVv0zeSR9dPHeOXzbYaJr8Tzpgg',
    appId: '1:372544211642:web:e50a7c9e04096d5bd85083',
    messagingSenderId: '372544211642',
    projectId: 'hueveria-project',
    authDomain: 'hueveria-project.firebaseapp.com',
    storageBucket: 'hueveria-project.appspot.com',
    measurementId: 'G-JSPCKD8Z4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANdeZdnKA8qECMJRFrRDp3qqB_k3y6jGM',
    appId: '1:372544211642:android:906106b86b0e7d71d85083',
    messagingSenderId: '372544211642',
    projectId: 'hueveria-project',
    storageBucket: 'hueveria-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYGpdiBVdXYAzTf-DeD1qJxfOjfleeeP4',
    appId: '1:372544211642:ios:491c6fc1327e1e71d85083',
    messagingSenderId: '372544211642',
    projectId: 'hueveria-project',
    storageBucket: 'hueveria-project.appspot.com',
    iosClientId: '372544211642-5cma6obds3thdrvmruep1th4m2t3a9ov.apps.googleusercontent.com',
    iosBundleId: 'com.example.hueveriaNietoInterna',
  );
}
